apiVersion: apps/v1
kind: Deployment
metadata:
  name: spree-frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: spree-frontend
  template:
    metadata:
      labels:
        app: spree-frontend
    spec:
      containers:
        - name: spree-frontend
          image: 
          ports:
            - containerPort: 4000
          env:
            - name: BACKEND_URL
              value: "http://spree-backend:3000"


